server:
  port: 6677
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ppchat?serverTimezone=UTC
    username: root
    password: Hsm12138
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB